# Enable the H2 web console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Tell Spring Data JPA to generate the tables automatically
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Explicitly tell Spring to use H2 (This forces it to forget about MySQL)
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=